/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/listings": {
    /**
     * Get listings
     * @description Retrieve paginated listings with optional filtering
     */
    get: operations["getListings"];
    /**
     * Create listing
     * @description Create a new marketplace listing
     */
    post: operations["createListing"];
  };
  "/api/listings/bulk": {
    /**
     * Create multiple listings
     * @description Create multiple marketplace listings in bulk
     */
    post: operations["createBulkListings"];
  };
  "/health": {
    /**
     * Health check
     * @description Returns API status
     */
    get: operations["health"];
  };
  "/api/listings/{id}": {
    /**
     * Get listing by ID
     * @description Retrieve a specific listing by its ID
     */
    get: operations["getListing"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description Request payload for creating a new marketplace listing */
    CreateListingRequest: {
      /**
       * @description Title of the item being sold
       * @example MacBook Pro 13-inch
       */
      title: string;
      /**
       * @description Detailed description of the item
       * @example Excellent condition MacBook Pro, barely used
       */
      description?: string;
      /**
       * @description Price of the item in USD
       * @example 1299.99
       */
      price: number;
      /**
       * @description Category of the item
       * @example Electronics
       */
      category?: string;
      /**
       * @description Condition of the item
       * @example Like New
       */
      condition?: string;
    };
    /** @description Marketplace listing response data */
    ListingResponse: {
      /** Format: uuid */
      id?: string;
      title?: string;
      description?: string;
      price?: number;
      category?: string;
      condition?: string;
      status?: string;
      /** Format: uuid */
      sellerId?: string;
      sellerName?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    PageListingResponse: {
      /** Format: int32 */
      totalPages?: number;
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      size?: number;
      content?: components["schemas"]["ListingResponse"][];
      /** Format: int32 */
      number?: number;
      sort?: components["schemas"]["SortObject"];
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components["schemas"]["PageableObject"];
      first?: boolean;
      last?: boolean;
      empty?: boolean;
    };
    PageableObject: {
      /** Format: int64 */
      offset?: number;
      sort?: components["schemas"]["SortObject"];
      unpaged?: boolean;
      /** Format: int32 */
      pageSize?: number;
      /** Format: int32 */
      pageNumber?: number;
      paged?: boolean;
    };
    SortObject: {
      empty?: boolean;
      unsorted?: boolean;
      sorted?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Get listings
   * @description Retrieve paginated listings with optional filtering
   */
  getListings: {
    parameters: {
      query?: {
        /** @description Page number (0-based) */
        page?: number;
        /** @description Page size */
        size?: number;
        /** @description Search query */
        q?: string;
        /** @description Category filter */
        category?: string;
        /** @description Status filter */
        status?: string;
        /** @description Minimum price */
        minPrice?: number;
        /** @description Maximum price */
        maxPrice?: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PageListingResponse"];
        };
      };
    };
  };
  /**
   * Create listing
   * @description Create a new marketplace listing
   */
  createListing: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateListingRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ListingResponse"];
        };
      };
    };
  };
  /**
   * Create multiple listings
   * @description Create multiple marketplace listings in bulk
   */
  createBulkListings: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateListingRequest"][];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ListingResponse"][];
        };
      };
    };
  };
  /**
   * Health check
   * @description Returns API status
   */
  health: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": {
            [key: string]: string;
          };
        };
      };
    };
  };
  /**
   * Get listing by ID
   * @description Retrieve a specific listing by its ID
   */
  getListing: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ListingResponse"];
        };
      };
    };
  };
}
